note/urls.py
from django.urls import path

from note import views

urlpatterns = [
    path("", views.index, name="index"),
    path("notes/", views.NoteListView.as_view(), name="note-list"),
    path(
        "notes/<int:pk>/",
        views.NoteDetailView.as_view(),
        name="note-detail"
    ),
    path(
        "notes/<int:pk>/update/",
        views.NoteUpdateView.as_view(),
        name="note-update"
    ),
    path(
        "notes/<int:pk>/delete/",
        views.NoteDeleteView.as_view(),
        name="note-delete"
    ),
    path("notes/create/", views.NoteCreateView.as_view(), name="note-create"),
    path(
        "note-groups/",
        views.NoteGroupListView.as_view(),
        name="note-group-list"
    ),
    path(
        "note-groups/<int:pk>/",
        views.NoteGroupDetailView.as_view(),
        name="note-group-detail"
    ),
    path(
        "note-groups/<int:pk>/update/",
        views.NoteGroupUpdateView.as_view(),
        name="note-group-update"
    ),
    path(
        "note-groups/<int:pk>/delete/",
        views.NoteGroupDeleteView.as_view(),
        name="note-group-delete"
    ),
    path(
        "note-groups/create/",
        views.NoteGroupCreateView.as_view(),
        name="note-group-create"
    ),

]

app_name = "note"

ooh_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls", namespace="users")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("note.urls", namespace="note")),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/includes/footer.html
<p class="footer-text"> 24 Boulevard Saint-Michel, Paris, France</p>
<p class="footer-text">Email: sancho@bourjois.com</p>
<p class="footer-text">Phone: +33-3-46-39-56-14</p>
<p class="footer-text">&copy; 2024 ooh!Notes. All rights reserved.</p>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link"><</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">></a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
{# +list-group-item <ul class="sidebar-nav list-group">#}
{% load static %}
<ul class="navbar">
  <li class="end-item"><a href="{% url 'note:index' %}"><img src="{% static "images/logoo.png" %}" class="logo" alt="logo" />ooh! Notes</a></li>
  <a class="position btn btn-light" href="{% url 'note:note-list' %}">Notes ✏️</a>
  <a class="position btn btn-light" href="{% url 'note:note-group-list' %}">Groups 📒</a>

  {% if user.is_authenticated %}
    <a class=" position btn btn-light" href="{{ user.get_absolute_url }}">Profile 👨🏻‍💻</a>
    <li class="position">
      <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <input type="submit" value="Log out 🚪" class="btn btn-light" />
      </form>
    </li>
  {% else %}
    <a class="position btn btn-dark" style="color: white;" href="{% url 'login'%}?next={{request.path}}">Log In</a>
  {% endif %}
</ul>