note/urls.py
from django.urls import path

from note import views

urlpatterns = [
    path("", views.index, name="index"),
    path("notes/", views.NoteListView.as_view(), name="note-list"),
    path(
        "notes/<int:pk>/",
        views.NoteDetailView.as_view(),
        name="note-detail"
    ),
    path(
        "notes/<int:pk>/update/",
        views.NoteUpdateView.as_view(),
        name="note-update"
    ),
    path(
        "notes/<int:pk>/delete/",
        views.NoteDeleteView.as_view(),
        name="note-delete"
    ),
    path("notes/create/", views.NoteCreateView.as_view(), name="note-create"),
    path(
        "note-groups/",
        views.NoteGroupListView.as_view(),
        name="note-group-list"
    ),
    path(
        "note-groups/<int:pk>/",
        views.NoteGroupDetailView.as_view(),
        name="note-group-detail"
    ),
    path(
        "note-groups/<int:pk>/update/",
        views.NoteGroupUpdateView.as_view(),
        name="note-group-update"
    ),
    path(
        "note-groups/<int:pk>/delete/",
        views.NoteGroupDeleteView.as_view(),
        name="note-group-delete"
    ),
    path(
        "note-groups/create/",
        views.NoteGroupCreateView.as_view(),
        name="note-group-create"
    ),

]

app_name = "note"

ooh_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls", namespace="users")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("note.urls", namespace="note")),
    path("__debug__/", include("debug_toolbar.urls")),
]

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path("register/", views.registration, name="sign-up"),
    path(
        "profile/<int:pk>/",
        views.TechUserDetailView.as_view(),
        name="profile"
    ),
    path(
        "profile/<int:pk>/update/",
        views.TechUserUpdateView.as_view(),
        name="profile-update"
    ),
    path(
        "profile/<int:pk>/delete/",
        views.TechUserDeleteView.as_view(),
        name="profile-delete"
    ),
    path(
        "profile/<int:pk>/coupon/",
        views.coupon_code_view,
        name="coupon"
    )
]

app_name = "users"

note/models.py
from django.contrib.auth import settings
from django.db import models
from django.urls import reverse


class TechTag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self) -> str:
        return self.name


class Note(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    resources = models.CharField(max_length=255, null=True, blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
    )
    tags = models.ManyToManyField(TechTag)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        default_related_name = "notes"

    def get_absolute_url(self):
        return reverse("note:note-detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.title} by {self.owner}"


class NoteGroup(models.Model):
    name = models.CharField(max_length=255)
    notes = models.ManyToManyField(Note)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    tag = models.ForeignKey(TechTag, on_delete=models.DO_NOTHING)

    class Meta:
        default_related_name = "note_groups"
        ordering = ["-created_at"]

    def get_absolute_url(self):
        return reverse("note:note-group-detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.name} by {self.owner}"

note/forms.py
from django import forms

from note.models import Note, TechTag, NoteGroup


class NoteForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=TechTag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Note
        fields = ("title", "body", "tags", "resources",)


class NoteGroupForm(forms.ModelForm):
    notes = forms.ModelMultipleChoiceField(
        queryset=Note.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = NoteGroup
        fields = ("name", "notes", "tag",)


class NoteSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"})
    )


class NoteGroupSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class TechTagFilterForm(forms.Form):
    tag = forms.ModelChoiceField(
        queryset=TechTag.objects.all(),
        widget=forms.RadioSelect,
        label="",
        required=False
    )

note/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from note.forms import (
    NoteForm,
    NoteGroupForm,
    NoteSearchForm,
    NoteGroupSearchForm,
    TechTagFilterForm
)
from note.models import Note, NoteGroup


def index(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        return render(request, "note/index.html")
    return render(request, "note/landing.html")


class NoteListView(LoginRequiredMixin, generic.ListView):
    model = Note
    paginate_by = 5

    def get_queryset(self) -> QuerySet:
        queryset = Note.objects.select_related("owner")
        form = NoteSearchForm(self.request.GET)
        tag = TechTagFilterForm(self.request.GET)

        if form.is_valid():
            queryset = queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )
        if tag.is_valid():
            if tag.cleaned_data["tag"]:
                queryset = queryset.filter(
                    tags=tag.cleaned_data["tag"]
                )

        return queryset

    def get_context_data(self, *args, object_list=None, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        tag = self.request.GET.get("tag", "")

        context["search_form"] = NoteSearchForm(
            initial={"title": title}
        )
        context["filter_form"] = TechTagFilterForm(
            initial={"tag": tag}
        )
        return context


class NoteDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = Note.objects.select_related("owner")


class NoteCreateView(LoginRequiredMixin, generic.CreateView):
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy("note:note-list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)


class NoteUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Note
    form_class = NoteForm

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner__id=self.request.user.id)


class NoteDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Note
    success_url = reverse_lazy("note:note-list")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner__id=self.request.user.id)


class NoteGroupListView(LoginRequiredMixin, generic.ListView):
    model = NoteGroup
    context_object_name = "note_group_list"
    template_name = "note/note_group_list.html"
    paginate_by = 5

    def get_queryset(self) -> QuerySet:
        queryset = NoteGroup.objects.select_related("owner")
        form = NoteGroupSearchForm(self.request.GET)
        tag = TechTagFilterForm(self.request.GET)

        if tag.is_valid():
            if tag.cleaned_data["tag"]:
                queryset = queryset.filter(
                    tag__name=tag.cleaned_data["tag"]
                )

        if form.is_valid():
            queryset = queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset

    def get_context_data(self, *args, object_list=None, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        tag = self.request.GET.get("tag", "")

        context["search_form"] = NoteGroupSearchForm(
            initial={"name": name}
        )
        context["filter_form"] = TechTagFilterForm(
            initial={"tag": tag}
        )
        return context


class NoteGroupDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = NoteGroup.objects.prefetch_related(
        "notes__owner"
    ).select_related("tag").select_related("owner")
    context_object_name = "note_group"
    template_name = "note/note_group_detail.html"


class NoteGroupCreateView(LoginRequiredMixin, generic.CreateView):
    model = NoteGroup
    form_class = NoteGroupForm
    template_name = "note/note_group_form.html"
    success_url = reverse_lazy("note:note-group-list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)


class NoteGroupUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = NoteGroup
    form_class = NoteGroupForm
    template_name = "note/note_group_form.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner__id=self.request.user.id)


class NoteGroupDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = NoteGroup
    template_name = "note/note_group_confirm_delete.html"
    success_url = reverse_lazy("note:note-group-list")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner__id=self.request.user.id)

templates/note/index.html
{% extends "base.html" %}

{% block content %}
  <div class="index-block">
    <h1 class="index-head">
      <span class="oh-yes">ooh Yes!</span>
      <br> Note-Taking Tips with Ooh! Notes
    </h1>
    <br>
    <h3>1. Capture Ideas Instantly</h3>
    <br>
    <p class="index-p">
      Whether it's a brilliant thought or a sudden burst of inspiration,
      don't let it slip away. Use Ooh! Notes to capture your ideas instantly, wherever you are.
      With quick access and intuitive controls, jotting down your thoughts has never been easier.
    </p>
    <br>
    <h3>2. Stay Organized with Tags</h3>
    <br>
    <p class="index-p">
      Keep your notes organized and easily searchable by utilizing tags. Assign relevant keywords or categories to your
      notes using Ooh! Notes' tagging system. This simple yet powerful feature helps you find what you need, when you
      need it, with just a few clicks.
    </p>
    <br>
    <h3>3. Review and Reflect</h3>
    <br>
    <p class="index-p">
      Regularly review and reflect on your notes to reinforce learning and spark new ideas. Use Ooh! Notes' powerful
      search and filtering capabilities to revisit past notes, identify patterns, and gain new insights. Your notes
      aren't just for capturing information – they're valuable tools for personal growth and development.
    </p>
    <br>
    <a class="index-btn btn btn-dark" href="{% url 'note:note-create' %}">Create a note!</a>
    <br>
    <br>
    <br>
  </div>
{% endblock %}

templates/note/landing.html
{% extends "base.html" %}

{% block content %}

  <div class="index-block">
    <h1 class="index-head">ooh! Your Notes</h1>
    <br>
    <h3>Your Ultimate Note-Taking Companion</h3>
    <br>
    <p class="index-p">Welcome to Ooh! Notes – the ultimate solution for all your note-taking needs.
      Say goodbye to scattered thoughts and disorganized ideas. With Ooh! Notes, jotting down your ideas, thoughts,
      and to-dos has never been easier or more enjoyable.
    </p>
    <br>
    <h4><strong>Features:</strong></h4>
    <br>
    <p class="index-p">
      <strong>Simple and Intuitive:</strong> Ooh! Notes is designed to be simple and intuitive,
      allowing you to focus on capturing your ideas without any distractions.
    </p>
    <br>
    <p class="index-p">
      <strong>Organize with Ease:</strong> Keep your notes organized effortlessly with our intuitive tagging system.
      Categorize your notes for easy access and retrieval.
    </p>
    <br>
    <a class="index-btn btn btn-dark" href="{% url 'users:sign-up' %}">Start now!</a>
    <br>
    <br>
    <br>
  </div>

{% endblock %}

templates/note/note_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete note?</h1>
  <div>
    <form action="" method="post" style ='float: left; padding: 5px;'>
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
    <form action="{% url 'note:note-detail' pk=note.id %}" method="get" style='float: left; padding: 5px;'>
      {% csrf_token %}

      <input type="submit" value="Cancel" class="btn btn-light">
    </form>
  </div>

{% endblock %}

templates/note/note_detail.html
{% extends "base.html" %}

{% block content %}

  <div class="note-view">
    <h1 class="title">
      {{ note.title }}
      <a href="{% url 'note:note-list' %}" type="submit" class="btn btn-light">❌</a>
      {% if user.id == note.owner.id %}
        <a href="{% url 'note:note-update' pk=note.id %}" class="btn btn-outline-dark link-to-page">
          ✍️
        </a>

        <a href="{% url 'note:note-delete' pk=note.id %}" class="btn btn-outline-danger link-to-page">
          🗑️
        </a>
      {% endif %}
    </h1>
    <div class="meta">
      <span class="author">
        <a href="{% url 'users:profile' pk=note.owner.id %}">
          {{ note.owner.username }},
        </a>
      </span>
      <span class="time">Date: {{ note.created_at }}</span>
    </div>
    <div class="tags">
      Tags:
      {% for tag in note.tags.all %}
        <span class="tag">{{ tag.name }}</span>;
      {% endfor %}
    </div>
    <hr>
    <div class="body">
      {{ note.body }}
    </div>
    <div>
      {% if note.resources %}
        <hr>
        <p>
          <strong>Resources: </strong>
          {{ note.resources }}
        </p>
      {% endif %}
    </div>
  </div>


{% endblock %}

templates/note/note_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="col-md-10 form-container">
    <a href="{% url 'note:note-list' %}" type="submit" class="btn">❌</a>

    <h2 class="text-center">{{ object|yesno:"Update,Create" }} Note</h2>
    <br>
    <form method="POST" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <hr>
      <button type="submit" class="btn btn-dark btn-block">Create</button>
    </form>
  </div>


{% endblock %}

templates/note/note_group_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete group?</h1>
  <form action="" method="post" style ='float: left; padding: 5px;'>
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  <form action="{% url 'note:note-group-detail' pk=notegroup.id %}" method="get" style ='float: left; padding: 5px;'>
    {% csrf_token %}

    <input type="submit" value="Cancel" class="btn btn-light">
  </form>

{% endblock %}

templates/note/note_group_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="note-view">
    <h1 class="title">
      {{ note_group.name }}
      <a href="{% url 'note:note-list' %}" type="submit" class="btn btn-light">❌</a>
      {% if user.id == note_group.owner.id %}
        <a href="{% url 'note:note-group-update' pk=note_group.id %}" class="btn btn-outline-dark link-to-page">
          ✍️
        </a>

        <a href="{% url 'note:note-group-delete' pk=note_group.id %}" class="btn btn-outline-danger link-to-page">
          🗑️
        </a>
      {% endif %}
    </h1>
    <div class="meta">
      <span class="author">Created by:
        <a href="{% url 'users:profile' pk=note_group.owner.id %}">
          {{ note_group.owner.username }}
        </a>
      </span>
      <span class="time">Date: {{ note_group.created_at }}</span>
    </div>
    <div class="tags">
      Topic: <span class="tag">{{ note_group.tag.name }}</span>
    </div>
    <div class="body">
      {% for note in note_group.notes.all %}
        <hr>
        🗒
        <a href="{% url 'note:note-detail' pk=note.id %}">
          {{ note.title }}
        </a>by <a href="{% url 'users:profile' pk=note.owner.id  %}">{{ note.owner.username }}</a>
      {% endfor %}
    </div>
  </div>

{% endblock %}

templates/note/note_group_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="col-md-10 form-container to-low">
    <a href="{% url 'note:note-group-list' %}" type="submit" class="btn">❌</a>

    <h2 class="text-center">{{ object|yesno:"Update,Create" }} Note Group</h2>
    <br>
    <form method="POST" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <hr>
      <button type="submit" class="btn btn-dark btn-block">Create</button>
    </form>
  </div>

{% endblock %}

templates/note/note_group_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div>
    <h1>
      Note Groups
      <a href="{% url 'note:note-group-create' %}" class="btn btn-outline-dark link-to-page">
        +
      </a>
    </h1>

    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-outline-light" type="submit" value="🔍">
    </form>
    <br>

    <form action="" method="get">
      {{ filter_form|crispy }}
      <input class="btn btn-dark" type="submit" value="Apply filter">
      <a href="{% url 'note:note-group-list' %}" class="btn btn-secondary link-to-page">
        Clear
      </a>
    </form>
    <br>

    {% if note_group_list %}
      <ul class="note-list">
        {% for group in note_group_list %}
          <li class="note-item">
            📒 <a href="{% url 'note:note-group-detail' pk=group.id %}">{{ group.name }}</a>
            <span class="note-author">by <a
                href="{% url 'users:profile' pk=group.owner.id %}">{{ group.owner.username }}</a></span>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no groups...</p>
    {% endif %}
  </div>
{% endblock %}

templates/note/note_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div>
    <h1>
      Notes
      <a href="{% url 'note:note-create' %}" class="btn btn-outline-dark link-to-page">
        +
      </a>
    </h1>

    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-outline-light" type="submit" value="🔍">
    </form>
    <br>

    <form action="" method="get" class="filter-form">
      {{ filter_form|crispy }}
      <div class="form-buttons">
        <input class="btn btn-dark" type="submit" value="Apply filter">
        <a href="{% url 'note:note-list' %}" class="btn btn-secondary link-to-page">
          Clear
        </a>
      </div>
    </form>
    <br>

    {% if note_list %}
      <ul class="note-list">
        {% for note in note_list %}
          <li class="note-item">
            🗒 <a href="{% url 'note:note-detail' pk=note.id %}">
            {{ note.title }}
          </a>
            <span class="note-author">by <a
                href="{% url 'users:profile' pk=note.owner.id %}">{{ note.owner.username }}</a></span>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no notes...</p>
    {% endif %}
  </div>
{% endblock %}