note/urls.py
from django.urls import path

from note import views

urlpatterns = [
    path("", views.index, name="index"),
    path("notes/", views.NoteListView.as_view(), name="note-list"),
    path(
        "notes/<int:pk>/",
        views.NoteDetailView.as_view(),
        name="note-detail"
    ),
    path(
        "notes/<int:pk>/update/",
        views.NoteUpdateView.as_view(),
        name="note-update"
    ),
    path(
        "notes/<int:pk>/delete/",
        views.NoteDeleteView.as_view(),
        name="note-delete"
    ),
    path("notes/create/", views.NoteCreateView.as_view(), name="note-create"),
    path(
        "note-groups/",
        views.NoteGroupListView.as_view(),
        name="note-group-list"
    ),
    path(
        "note-groups/<int:pk>/",
        views.NoteGroupDetailView.as_view(),
        name="note-group-detail"
    ),
    path(
        "note-groups/<int:pk>/update/",
        views.NoteGroupUpdateView.as_view(),
        name="note-group-update"
    ),
    path(
        "note-groups/<int:pk>/delete/",
        views.NoteGroupDeleteView.as_view(),
        name="note-group-delete"
    ),
    path(
        "note-groups/create/",
        views.NoteGroupCreateView.as_view(),
        name="note-group-create"
    ),

]

app_name = "note"

ooh_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls", namespace="users")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("note.urls", namespace="note")),
    path("__debug__/", include("debug_toolbar.urls")),
]

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path("register/", views.registration, name="sign-up"),
    path(
        "profile/<int:pk>/",
        views.TechUserDetailView.as_view(),
        name="profile"
    ),
    path(
        "profile/<int:pk>/update/",
        views.TechUserUpdateView.as_view(),
        name="profile-update"
    ),
    path(
        "profile/<int:pk>/delete/",
        views.TechUserDeleteView.as_view(),
        name="profile-delete"
    ),
    path(
        "profile/<int:pk>/coupon/",
        views.coupon_code_view,
        name="coupon"
    )
]

app_name = "users"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from note.models import TechTag


class TechUser(AbstractUser):
    skill = models.ForeignKey(
        to=TechTag,
        on_delete=models.DO_NOTHING,
        related_name="tech_users",
    )

    class Meta:
        ordering = ("username",)

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator

from users.models import TechUser


class TechUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = TechUser
        fields = UserCreationForm.Meta.fields + (
            "skill",
            "first_name",
            "last_name",
            "email",
        )


class TechUserUpdateForm(forms.ModelForm):
    class Meta:
        model = TechUser
        fields = (
            "username", "skill", "first_name", "last_name", "email",
        )


def validate_coupon_code(coupon_code_input: str):
    coupon_code = RegexValidator(
        regex=r"^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$",
        message=(
            "Coupon code includes numbers and capital letters, "
            "and has a next format -> 'XXXX-XXXX-XXXX'"
        ),
        code="invalid_coupon_code"
    )
    coupon_code(coupon_code_input)


class CouponForm(forms.Form):
    coupon_code = forms.CharField(
        max_length=255,
        required=True,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter a coupon code..."
            }
        ),
        validators=[validate_coupon_code]
    )

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from users.forms import TechUserCreationForm, TechUserUpdateForm, CouponForm
from users.models import TechUser


def registration(request: HttpRequest) -> HttpResponse:
    form = TechUserCreationForm()

    if request.method == "POST":
        form = TechUserCreationForm(request.POST)

        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )
            login(request, new_user)
            return HttpResponseRedirect(reverse_lazy("note:index"))

    return render(request, 'registration/sign_up.html', {'form': form})


class TechUserDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = TechUser.objects.prefetch_related("note_groups")
    template_name = "users/tech_user_detail.html"


class TechUserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TechUser
    template_name = "users/tech_user_form.html"
    form_class = TechUserUpdateForm

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(id=self.request.user.id)


class TechUserDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TechUser
    template_name = "users/tech_user_confirm_delete.html"
    success_url = reverse_lazy("note:index")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(id=self.request.user.id)


@login_required
def coupon_code_view(request: HttpRequest, pk: int) -> HttpResponse:
    form = CouponForm()

    if request.method == "POST":
        form = CouponForm(request.POST)

        if form.is_valid():
            return render(request, 'users/coupon_code_gift.html')

    return render(request, 'users/coupon_code_form.html', {'form': form})

templates/users/coupon_code_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="col-md-11 form-container to-low">
    <a href="{% url 'users:profile' pk=user.id %}" type="submit" class="btn">❌</a>

    <h1 class="mb-4 text-center">
      Enter your coupon code!
    </h1>
    <h3 class="text-center mb-4">Who knows, maybe it's your lucky day!</h3>
    <form method="POST" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <hr>
      <div class="buttons-container">
        <button type="submit" class="btn btn-dark btn-block">Validate</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/users/coupon_code_gift.html
{% extends "base.html" %}

{% block content %}
  <div class="index-block">
    <h1 class="index-head">
      <span class="oh-yes">Congratulations!</span>
      <br> You can hire a CEO of "ooh! Notes Inc."
    </h1>
    <br>
    <h3>Contact this talented developer!</h3>
    <br>
    <p class="index-p">
      <strong>Email: </strong>chebukin404@gmail.com
    </p>
    <br>
    <a class="index-btn btn btn-outline-success" href="">Send a mail!</a>
    <a class="index-btn btn btn-outline-dark" href="{% url 'users:profile' pk=user.id %}">Back to profile!</a>
    <br>
    <br>
    <br>
  </div>
{% endblock %}

templates/users/tech_user_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete profile?</h1>
  <br>
  <h4><strong>WARNING!</strong> All notes and groups will be deleted as well</h4>
  <hr>
  <form action="" method="post" style='float: left; padding: 5px;'>
    {% csrf_token %}

    <input type="submit" value="Delete" class="btn btn-danger">
  </form>
  <form action="{% url 'users:profile' pk=user.id %}" method="get" style='float: left; padding: 5px;'>
    {% csrf_token %}

    <input type="submit" value="Cancel" class="btn btn-light">
  </form>
{% endblock %}

templates/users/tech_user_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h1>
      @{{ techuser.username }}
      {% if user.id == techuser.id %}
        <a href="{% url 'users:profile-update' pk=user.id %}" class="btn btn-outline-dark link-to-page">
          ✍️
        </a>
        <a href="{% url 'users:profile-delete' pk=user.id %}" class="btn btn-outline-danger link-to-page">
          🗑️
        </a>
        <a href="{% url 'users:coupon' pk=user.id %}" class="btn btn-outline-success link-to-page">
          🎟
        </a>
      {% endif %}
    </h1>
    <br>
    <p>👨‍🏫 {{ techuser.skill }} professor</p>

    {% if techuser.first_name or techuser.last_name %}
      <p>
        {{ techuser.first_name }} {{ techuser.last_name }}
      </p>
    {% endif %}
    <p><strong>email: </strong>{% if techuser.email %}{{ techuser.email }}{% else %}no email :({% endif %}</p>
    <br>

    <button class="btn btn-dark" onclick="showNotes()">
      {% if user.id == techuser.id %}My {% endif %}Notes
    </button>
    <button class="btn btn-outline-dark" onclick="showNoteGroups()">
      {% if user.id == techuser.id %}My {% endif %}Note Groups
    </button>
    <hr>

    <div id="notesContent" class="hidden">
      <h4>{% if user.id == techuser.id %}My {% endif %}Notes</h4>
      {% if techuser.notes.all %}
        <ul class="note-list">
          {% for note in techuser.notes.all %}
            <a style="text-decoration: none;" href="{% url 'note:note-detail' pk=note.id %}">
              <p class="note-item">🗒 {{ note.title }}</p>
            </a>
          {% endfor %}
        </ul>
      {% else %}
        <p>There are no notes...</p>
      {% endif %}
    </div>

    <div id="noteGroupsContent" class="hidden">
      <h4>{% if user.id == techuser.id %}My {% endif %}Note Groups</h4>
      {% if techuser.note_groups.all %}
        <ul class="note-list">
          {% for group in techuser.note_groups.all %}
            <a style="text-decoration: none;" href="{% url 'note:note-group-detail' pk=group.id %}">
              <p class="note-item"><span class="emoji">📒</span> {{ group.name }}</p>
            </a>
          {% endfor %}
        </ul>
      {% else %}
        <p>There are no groups...</p>
      {% endif %}
    </div>

    <script>
        function showNotes() {
            document.getElementById('notesContent').style.display = 'block';
            document.getElementById('noteGroupsContent').style.display = 'none';
        }

        function showNoteGroups() {
            document.getElementById('notesContent').style.display = 'none';
            document.getElementById('noteGroupsContent').style.display = 'block';
        }
    </script>

  </div>
{% endblock %}

templates/users/tech_user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="col-md-10 form-container">
    <a href="{% url 'users:profile' pk=user.id %}" type="submit" class="btn">❌</a>

    <h2 class="text-center">
      Update Personal Info
    </h2>
    <br>
    <form method="POST" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <hr>
      <div class="buttons-container">
        <button type="submit" class="btn btn-dark btn-block">Update</button>
      </div>
    </form>
  </div>
{% endblock %}